/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_h21W3I0pW",
    "aws_user_pools_web_client_id": "7eu85jkq18d00bmm9dp0l6lmqe",
    "oauth": {
        "domain": "phylogenyexplorer21dbf8aa-21dbf8aa-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://phylogenyexplorerproject.com/",
        "redirectSignOut": "https://phylogenyexplorerproject.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
