export const AUTH_USER_TOKEN_KEY = 'ReactAmplify.TokenKey';

export const SOCIAL = {
  FACEBOOK: 'facebook',
  GITHUB: 'github',
  GOOGLE: 'google',
  GOOGLE_PLAY: 'googleStore',
  INSTAGRAM: 'instagram',
  ITUNES_STORE: 'itunes',
  LINKEDIN: 'linkedin',
  REDDIT: 'reddit',
  TIKTOK: 'tiktok',
  TWITTER: 'twitter',
  YOUTUBE: 'youtube',
};

export const COLOURS = {
  primary: '#06C9AF',
  dprimary: '#009780',
  lprimary: '#61FDE1',
  secondary: '#AF996B',
  dsecondary: '#7E6B3F',
  lsecondary: '#E2CA9A',
  warning: '#AF996B',
  error: '#C90620',
  success: '#06C94E',
  white: '#FFF',
  offWhite: '#EEE',
  vvlgrey: '#D5D6D8',
  vlgrey: '#B6BCC1',
  lgrey: '#97A1AA',
  grey: '#7F8D98',
  dgrey: '#687A87',
  vdgrey: '#5C6B76',
  vvdgrey: '#4C5760',
  offBlack: '#3D454B',
  black: '#2B3034',
  [SOCIAL.FACEBOOK]: '#1877F2',
  [SOCIAL.GITHUB]: '#000',
  [SOCIAL.GOOGLE]: '#518EF8',
  [SOCIAL.GOOGLE_PLAY]: '#00D2FF',
  [SOCIAL.INSTAGRAM]: '#EF0176',
  [SOCIAL.ITUNES_STORE]: '#D13BF2',
  [SOCIAL.LINKEDIN]: '#0073B0',
  [SOCIAL.REDDIT]: '#FF4500',
  [SOCIAL.TIKTOK]: '#444',
  [SOCIAL.TWITTER]: '#1DA1F2',
  [SOCIAL.YOUTUBE]: '#FF0000',
};

export const SOCIAL_TITLES = {
  [SOCIAL.FACEBOOK]: 'Facebook',
  [SOCIAL.GITHUB]: 'GitHub',
  [SOCIAL.GOOGLE]: 'Google',
  [SOCIAL.GOOGLE_PLAY]: 'Google Play',
  [SOCIAL.INSTAGRAM]: 'Instagram',
  [SOCIAL.ITUNES_STORE]: 'Itunes Store',
  [SOCIAL.LINKEDIN]: 'LinkedIn',
  [SOCIAL.REDDIT]: 'Reddit',
  [SOCIAL.TIKTOK]: 'TikTok',
  [SOCIAL.TWITTER]: 'Twitter',
  [SOCIAL.YOUTUBE]: 'YouTube',
};
